# Site settings
title: "MADness"
description: A Template for Jekyll

# Files
baseurl: dist
pagesdir:
# In _config.yml
defaults:
  -
    scope:
      path: "dist"
      type: "pages"
    values:
      layout: ""
      author: ""
      category: ""