# Site settings
title: "MADness"
description: A Template for Jekyll

# Files
baseurl:
pagesdir: dist
# In _config.yml
defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: ""
      author: ""
      category: ""