# site settings
title: Blog
subtitle: by HTML5 UP
email: email@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
#baseurl: "/home" # the subpath of your site, e.g. /blog
url: github.io
author: Me
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
layouts_dir         : _layouts
sass_dir            : _sass
collections:
  posts:
    output          : true

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true