# Site settings
title: "MADness"
description: A Template for Jekyll

# Files
baseurl: /pages
url: "https://carlosal1015.github.io"

#dependencies
# Gems
plugins:
- jekyll-paginate

exclude: ["README.md"]