baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carlosal1015.github.io/"
author: Oromion
title: Oromion's blog
description: Blog about mathematics, TeX and programming.
avatar: /assets/img/ogp.png
favicon: /assets/img/ogp.png
language: en

# Icons
icons:
  rss: true
  email: caznaranl@uni.pe
  github: carlosal1015
  twitter: carlosal1015
  reddit: carlosal1015
  stack_exchange: https://stackexchange.com/users/9558603/oromion
  wordpress: blogdeoromion
  youtube: UC0dDIu9Ppa8BMXrNksA5oYA

# Prettify url.
permalink: pretty # /:categories/:year/:month/:day/:title/

katex: true # Enable if using math markup

# Localizations.
str_next: Next
str_prev: Prev
str_read_more: Read more ...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

# Recent posts.
recent_posts_num: 5

# Pagination.
paginate: 10
paginate_path: page/:num

ogp:
  image_url: //carlosal1015.github.io/assets/img/ogp.png

# Plugins.
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji

# - jekyll-multiple-languages-plugin

# Styles: see "_sass/base/_variables.scss"
# !! Danger zone !!
include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
#languages: ["en", "de", "es"]